### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by dkamdar** [bentrevor/vlc-total-playlist-duration-extension#1]
Hi,

Following the Install steps given in Readme.md, I copied the script (simple-time.lua) into directory 

lua dk$ pwd
**/Applications/VLC.app/Contents/MacOS/share/lua**
lua dk$ ls -lart
total 8
-rwxr-xr-x@  1 dk  staff  2330 Jan 17  2013 **simple-time.lua**
drwxr-xr-x   7 dk  staff   238 Jul 31  2013 sd
drwxr-xr-x   5 dk  staff   170 Jul 31  2013 modules
drwxr-xr-x   6 dk  staff   204 Jul 31  2013 meta
drwxr-xr-x  10 dk  staff   340 Jul 31  2013 intf
drwxr-xr-x  19 dk  staff   646 Jul 31  2013 http
drwxr-xr-x   5 dk  staff   170 Jul 31  2013 ..
drwxr-xr-x  29 dk  staff   986 Aug 12 00:22 playlist
drwxr-xr-x   9 dk  staff   306 Aug 12 00:22 .

However when I run VLC after quitting, I am not able to find the View menu item or "playlist total duration item"

Am I missing something?

I am using MAC OS X - Version - 10.9.4
and
VLC Version - 2.0.8

Thanks,
Dev.

**Comment by bentrevor** [comment]
Hi @dkamdar, this script was written for the linux version of VLC, so you might need to modify it a little to make it work for OSX.  You'll probably want to drop the `.lua` file somewhere like `/Applications/VLC.app/Contents/MacOS/share/lua/extensions/`, but then I'm not sure where it will show up in the menus.

**Comment by dkamdar** [comment]
Cool, @bentrevor. Thanks for the tip ... that just worked. 

You can add this to the readme.md ... so mac users can also use this.

Heres the steps I followed.
1. Created a new directory called **extensions** in folder - `/Applications/VLC.app/Contents/MacOS/share/lua/`
2. Then copied the script - **simple-time.lua** to the new location
   `/Applications/VLC.app/Contents/MacOS/share/lua/extensions`
3. Then restarted VLC and searched for duration under help menu and Voila! It pointed me to the location where the menu item was ... **VLC -> Extensions -> Playlist total duration.**

![screen shot 2014-08-18 at 1 47 27 am](https://cloud.githubusercontent.com/assets/1485304/3945645/3d4d78f4-264c-11e4-9a0e-dc0e3b5e66a0.png)

**Comment by bentrevor** [comment]
Awesome, thanks @dkamdar!  I put it in the readme.
